name: CentOS 9 QEMU Lab

on:
  workflow_dispatch:

jobs:
  centos-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:

      # =========================================================
      # 1. Install QEMU and required tools
      # =========================================================

      - name: Install QEMU and Required Tools
        shell: bash
        run: |
          set -e

          sudo apt-get update

          sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils \
            cloud-image-utils \
            openssh-client \
            sshpass \
            netcat-openbsd \
            curl \
            wget

          echo "======================================"
          echo "QEMU VERSION"
          echo "======================================"

          qemu-system-x86_64 --version
          qemu-img --version


      # =========================================================
      # 2. Check KVM
      # =========================================================

      - name: Check KVM
        shell: bash
        run: |
          set -e

          echo "======================================"
          echo "CHECKING KVM"
          echo "======================================"

          if [ -e /dev/kvm ]; then
            echo "KVM is available."
            ls -l /dev/kvm
          else
            echo "WARNING: /dev/kvm is NOT available."
            echo "QEMU will use software emulation."
          fi


      # =================================================
